apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
